Repository mc2-center/data-models, pull requests merged in 2024-07, with the labels that each got.

#113 [fix] table rendering for "All Terms" table
  docs/valid_values/all_terms.md
Labels: documentation, non-release

#119 Multispecies fix for 6.0.1
  modules/shared/dataset_species.csv
Labels: patch

#123 Add FileView, Study, and terms for light sheet microscopy dataset
  all_valid_values.csv
  docs/model/file.md
  docs/model/study.md
  docs/valid_values/file.md
  mc2.model.csv
  mc2.model.jsonld
  mkdocs.yml
  modules/biospecimen/annotationProperty.csv
  modules/dataset/annotationProperty.csv
  modules/file/annotationProperty.csv
  modules/mapping.yaml
  modules/publication/annotationProperty.csv
  modules/shared/annotationProperty.csv
  modules/shared/assay.csv
  modules/shared/dataset_file_format.csv
  modules/shared/dataset_species.csv
  modules/sharingPlans/annotationProperty.csv
  modules/study/annotationProperty.csv
  scripts/hooks.py
  templates/FileView.csv
  templates/Study.csv
Labels: minor

#122 New tool schema update
  modules/tool/annotationProperty.csv
Labels: major

#126 Update file.md
  docs/valid_values/file.md
Labels: bug, patch

#129 Toolview attribute update
  all_valid_values.csv
  mc2.model.csv
  mc2.model.jsonld
  modules/mapping.yaml
  modules/person/annotationProperty.csv
  modules/project/annotationProperty.csv
  modules/shared/boolean.csv
  modules/tool/annotationProperty.csv
  modules/tool/entity_role.csv
  modules/tool/entity_type.csv
Labels: bug, non-release

#130 Update ToolView.csv
  .github/ISSUE_TEMPLATE/prepare-data-release.md
  dca_config/dca-template-config.json
  docs/valid_values/tool.md
  templates/ToolView.csv
Labels: minor
