Repository mc2-center/data-models, pull requests merged in 2025-03, with the labels that each got.

#144 Added 3D ATAC-PALM assay to assay.csv
  modules/shared/assay.csv
Labels: minor

#175 Update institution_name.csv
  modules/institution/institution_alias.csv
  modules/institution/institution_name.csv
Labels: minor

#177 Add iconTag mappings for MC2 assays
  modules/shared/mc2_iconTag_map_3-4-25.csv
Labels: non-release

#174 Update entire site
  .gitignore
  README.md
  docs/assets/dca-tutorial/dca_demo_biospecimen_template.png
  docs/assets/dca-tutorial/select_dcc.png
  docs/assets/dca-tutorial/select_folder.png
  docs/assets/dca-tutorial/select_project.png
  docs/assets/dca-tutorial/select_template.png
  docs/assets/dca-tutorial/validate_submit_metadata.png
  docs/home/how-to-use-multiple-templates.md
  docs/home/tutorial.md
  docs/index.md
  docs/model/DataDSP.md
  docs/model/dataset.md
  docs/model/education.md
  docs/model/file.md
  docs/model/grant.md
  docs/model/person.md
  docs/model/publication.md
  docs/model/study.md
  docs/model/tool.md
  docs/valid_values/file.md
  docs/valid_values/sharingPlans.md
  mc2.model.csv
  mkdocs.yml
  modules/dataset/exampleColumn.csv
  modules/dataset/template.csv
  modules/education/exampleColumn.csv
  modules/education/template.csv
  modules/file/annotationProperty.csv
  modules/file/exampleColumn.csv
  modules/file/template.csv
  modules/grant/exampleColumn.csv
  modules/grant/template.csv
  modules/person/exampleColumn.csv
  modules/person/template.csv
  modules/publication/exampleColumn.csv
  modules/publication/template.csv
  modules/sharingPlans/exampleColumn.csv
  modules/sharingPlans/template.csv
  modules/study/exampleColumn.csv
  modules/study/template.csv
  modules/tool/exampleColumn.csv
  modules/tool/template.csv
  scripts/hooks.py
Labels: documentation, non-release
